### ISSUE TITLE
problem with joins using data from a pail

### ISSUE THREAD

**Issue by robinkraft** [wri/forma-clj#60]
Using the [local pail dataset](http://formareset.s3.amazonaws.com/local_2012-06-21.zip) we've concocted, we're having trouble joining static datasets a la [static-src](https://github.com/reddmetrics/forma-clj/blob/feature/deliver/src/clj/forma/hadoop/jobs/scatter.clj#L68-80).

Extracting values from the thrift objects in the pail works fine, but the join fails completely.

Sample data and code here: https://gist.github.com/3035928

**Comment by sritchie** [comment]
@eightysteele did you ever look into this?

**Comment by eightysteele** [comment]
@sritchie https://twitter.com/eightysteele/status/219962902088646656
